services:
  dependencies:
    image: "kubernetes-pytorch-distributed-data-parallel-dependencies"
    build:
      context: "."
      target: "dependencies"

  development:
    image: "kubernetes-pytorch-distributed-data-parallel-development"
    build:
      context: "."
      target: "development"
    
    tty: True

    volumes:
      - ./source:/opt/source
  
  production:
    image: "kubernetes-pytorch-distributed-data-parallel-production"
    build:
      context: "."
      target: "production"